/**
 * login actions
 */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

/**
 * register actions
 */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const SERVICE_PROVIDER_LOGIN_SUCCESS = "SERVICE_PROVIDER_LOGIN_SUCCESS";
export const SERVICE_PROVIDER_LOGIN_ERROR = "SERVICE_PROVIDER_LOGIN_ERROR";

/**
 * customer actions
 */

export const FETCH_PRFOILE_SUCCESS = "FETCH_PRFOILE_SUCCESS";
export const FETCH_PRFOILE_ERROR = "FETCH_PRFOILE_ERROR";

export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_ERROR = "CREATE_SERVICE_ERROR";

export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_ERROR = "UPDATE_SERVICE_ERROR";

export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_ERROR = "FETCH_SERVICES_ERROR";

export const FETCH_SERVICE_PROVIDER_BY_TYPE_SUCCESS =
  "FETCH_SERVICE_PROVIDER_BY_TYPE_SUCCESS";
export const FETCH_SERVICE_PROVIDER_BY_TYPE_ERROR =
  "FETCH_SERVICE_PROVIDER_BY_TYPE_ERROR";

/**
 * service provider
 */

export const FETCH_SP_PROFILE_SUCCESS = "FETCH_SP_PROFILE_SUCCESS";
export const FETCH_SP_PROFILE_ERROR = "FETCH_SP_PROFILE_ERROR";

export const MODIFY_SERVICE_SUCCESS = "MODIFY_SERVICE_SUCCESS";
export const MODIFY_SERVICE_ERROR = "MODIFY_SERVICE_ERROR";

export const FETCH_CS_SERVICES_SUCCESS = "FETCH_CS_SERVICES_SUCCESS";
export const FETCH_CS_SERVICES_ERROR = "FETCH_CS_SERVICES_ERROR";

/**
 * admin actions
 */

export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";
export const FETCH_ALL_ERROR = "FETCH_ALL_ERROR";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR = "DELETE_DATA_ERROR";
